[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NEXT_USE_NETLIFY_EDGE = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  external_node_modules = ["puppeteer-core", "@sparticuz/chromium"]

[[redirects]]
  from = "/*"
  to = "/.next/server/pages/:splat"
  status = 200
